const tools = [
  // Money 💰
  { id: 'salary', name: 'Salary Calculator', icon: '💰', desc: 'Monthly, weekly, daily, hourly salary from annual income', url: 'tools/salary-calculator.html', phase: 1 },
  { id: 'ctc', name: 'CTC Calculator', icon: '💼', desc: 'Break down Cost to Company — base, HRA, allowances, deductions', url: 'tools/ctc-calculator.html', phase: 1 },
  { id: 'ctc2inhand', name: 'CTC to In-Hand', icon: '🏦', desc: 'Convert CTC to actual monthly in-hand salary after deductions', url: 'tools/ctc-to-inhand-calculator.html', phase: 1 },
  { id: 'inhand2ctc', name: 'In-Hand to CTC', icon: '🔄', desc: 'Reverse calculate CTC from desired take-home salary', url: 'tools/inhand-to-ctc-calculator.html', phase: 1 },
  { id: 'gst', name: 'GST/VAT Calculator', icon: '🧮', desc: 'Add or remove GST/VAT/SST — India, UK, EU, Australia, Singapore, UAE', url: 'tools/gst-calculator.html', phase: 1 },
  { id: 'emi', name: 'EMI Calculator', icon: '🏠', desc: 'Monthly EMI, total interest, and payment breakdown for any loan', url: 'tools/emi-calculator.html', phase: 1 },
  { id: 'sip', name: 'SIP Calculator', icon: '📈', desc: 'Estimate returns on monthly SIP mutual fund investments', url: 'tools/sip-calculator.html', phase: 1 },
  { id: 'tax', name: 'Income Tax Calculator', icon: '🧾', desc: 'Compare old vs new tax regime — see which saves you more', url: 'tools/income-tax-calculator.html', phase: 1 },
  { id: 'hra', name: 'HRA Calculator', icon: '🏘️', desc: 'HRA exemption and tax savings on house rent allowance', url: 'tools/hra-calculator.html', phase: 1 },
  { id: 'pf', name: 'PF Calculator', icon: '🏢', desc: 'Estimate Provident Fund / retirement balance at retirement', url: 'tools/pf-calculator.html', phase: 1 },
  { id: 'gratuity', name: 'Gratuity Calculator', icon: '🎁', desc: 'Calculate gratuity amount based on years of service', url: 'tools/gratuity-calculator.html', phase: 1 },
  { id: 'bonus', name: 'Bonus Calculator', icon: '🎉', desc: 'Statutory, performance, or fixed bonus with tax impact', url: 'tools/bonus-calculator.html', phase: 1 },
  { id: 'overtime', name: 'Overtime Calculator', icon: '⏰', desc: 'Overtime pay at 1.5x/2x/2.5x rate from monthly salary', url: 'tools/overtime-calculator.html', phase: 1 },
  { id: 'leave', name: 'Absent & Leave Calculator', icon: '📅', desc: 'Salary deduction for absent, paid leave, sick leave & LWP', url: 'tools/absent-leave-calculator.html', phase: 1 },
  { id: 'notice', name: 'Notice Period Calculator', icon: '📋', desc: 'Last working day with leave adjustment & buyout', url: 'tools/notice-period-calculator.html', phase: 1 },
  // Everyday 📅
  { id: 'age', name: 'Age Calculator', icon: '🎂', desc: 'Exact age in years, months, days, weeks, hours', url: 'tools/age-calculator.html', phase: 2 },
  { id: 'percentage', name: 'Percentage Calculator', icon: '％', desc: 'Percentage of, increase, decrease, change, ratio', url: 'tools/percentage-calculator.html', phase: 2 },
  { id: 'datediff', name: 'Date Difference', icon: '📆', desc: 'Calculate days, months, years between two dates', url: 'tools/date-difference-calculator.html', phase: 2 },
  { id: 'time', name: 'Time Calculator', icon: '⏱️', desc: 'Add, subtract, and convert time — hours, minutes, seconds', url: 'tools/time-calculator.html', phase: 2 },
  { id: 'unit-converter', name: 'Unit Converter', icon: '📏', desc: 'Convert length, weight, temperature, area, volume, speed', url: 'tools/unit-converter.html', phase: 2 },
  { id: 'currency-converter', name: 'Currency Converter', icon: '💱', desc: 'Convert between 30+ world currencies with live rates', url: 'tools/currency-converter.html', phase: 2 },
  // Utility Tools 🛠️
  { id: 'pdf', name: 'PDF Tools', icon: '📄', desc: 'Merge, split, compress, PDF to image, image to PDF', url: 'tools/pdf-tools.html', phase: 3 },
  { id: 'image', name: 'Image Tools', icon: '🖼️', desc: 'Resize, compress, convert, crop, rotate, watermark', url: 'tools/image-tools.html', phase: 3 },
  { id: 'qr', name: 'QR Generator', icon: '📱', desc: 'Create QR codes for URLs, text, WiFi, vCard, email', url: 'tools/qr-generator.html', phase: 3 },
  { id: 'resume', name: 'Resume Builder', icon: '📝', desc: 'Build a professional resume with live preview & PDF export', url: 'tools/resume-builder.html', phase: 3 },
  { id: 'writing', name: 'AI Writing Tools', icon: '✍️', desc: 'Summarizer, paraphraser, grammar checker, word counter', url: 'tools/ai-writing-tools.html', phase: 3 },
];